#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="EMCCN")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 擴充性方法定義
    partial void OnCreated();
    partial void InsertLOCK_WAGE(LOCK_WAGE instance);
    partial void UpdateLOCK_WAGE(LOCK_WAGE instance);
    partial void DeleteLOCK_WAGE(LOCK_WAGE instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::ConsoleApp1.Properties.Settings.Default.EMCCNConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<LOCK_WAGE> LOCK_WAGE
		{
			get
			{
				return this.GetTable<LOCK_WAGE>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.LOCK_WAGE")]
	public partial class LOCK_WAGE : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _YYMM;
		
		private string _SEQ;
		
		private string _KEY_MAN;
		
		private System.DateTime _KEY_DATE;
		
		private string _SALADR;
		
		private string _MENO;
		
    #region 擴充性方法定義
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnYYMMChanging(string value);
    partial void OnYYMMChanged();
    partial void OnSEQChanging(string value);
    partial void OnSEQChanged();
    partial void OnKEY_MANChanging(string value);
    partial void OnKEY_MANChanged();
    partial void OnKEY_DATEChanging(System.DateTime value);
    partial void OnKEY_DATEChanged();
    partial void OnSALADRChanging(string value);
    partial void OnSALADRChanged();
    partial void OnMENOChanging(string value);
    partial void OnMENOChanged();
    #endregion
		
		public LOCK_WAGE()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_YYMM", DbType="NVarChar(10) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string YYMM
		{
			get
			{
				return this._YYMM;
			}
			set
			{
				if ((this._YYMM != value))
				{
					this.OnYYMMChanging(value);
					this.SendPropertyChanging();
					this._YYMM = value;
					this.SendPropertyChanged("YYMM");
					this.OnYYMMChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SEQ", DbType="NVarChar(2) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SEQ
		{
			get
			{
				return this._SEQ;
			}
			set
			{
				if ((this._SEQ != value))
				{
					this.OnSEQChanging(value);
					this.SendPropertyChanging();
					this._SEQ = value;
					this.SendPropertyChanged("SEQ");
					this.OnSEQChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_MAN", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string KEY_MAN
		{
			get
			{
				return this._KEY_MAN;
			}
			set
			{
				if ((this._KEY_MAN != value))
				{
					this.OnKEY_MANChanging(value);
					this.SendPropertyChanging();
					this._KEY_MAN = value;
					this.SendPropertyChanged("KEY_MAN");
					this.OnKEY_MANChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_KEY_DATE", DbType="DateTime NOT NULL")]
		public System.DateTime KEY_DATE
		{
			get
			{
				return this._KEY_DATE;
			}
			set
			{
				if ((this._KEY_DATE != value))
				{
					this.OnKEY_DATEChanging(value);
					this.SendPropertyChanging();
					this._KEY_DATE = value;
					this.SendPropertyChanged("KEY_DATE");
					this.OnKEY_DATEChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SALADR", DbType="NVarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string SALADR
		{
			get
			{
				return this._SALADR;
			}
			set
			{
				if ((this._SALADR != value))
				{
					this.OnSALADRChanging(value);
					this.SendPropertyChanging();
					this._SALADR = value;
					this.SendPropertyChanged("SALADR");
					this.OnSALADRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_MENO", DbType="NVarChar(50) NOT NULL", CanBeNull=false)]
		public string MENO
		{
			get
			{
				return this._MENO;
			}
			set
			{
				if ((this._MENO != value))
				{
					this.OnMENOChanging(value);
					this.SendPropertyChanging();
					this._MENO = value;
					this.SendPropertyChanged("MENO");
					this.OnMENOChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
