//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ConsoleApp1.JbhrServiceCNReference46 {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransAttCardEntry", Namespace="http://schemas.datacontract.org/2004/07/JBHRService")]
    [System.SerializableAttribute()]
    public partial class TransAttCardEntry : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ADMINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttEndDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckDeleteAttendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckErrorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckFixOtField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CheckTimeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool CreateAttendField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPT_BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DEPT_EField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateBeginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private System.DateTime DateEndField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FixYymmField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOBR_BField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOBR_EField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalEndDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private ConsoleApp1.JbhrServiceCNReference46.SalaryConfig SalaryConfigField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_NAMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isContinueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool isFixYymmField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ADMIN {
            get {
                return this.ADMINField;
            }
            set {
                if ((this.ADMINField.Equals(value) != true)) {
                    this.ADMINField = value;
                    this.RaisePropertyChanged("ADMIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttEndDay {
            get {
                return this.AttEndDayField;
            }
            set {
                if ((this.AttEndDayField.Equals(value) != true)) {
                    this.AttEndDayField = value;
                    this.RaisePropertyChanged("AttEndDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANY {
            get {
                return this.COMPANYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYField, value) != true)) {
                    this.COMPANYField = value;
                    this.RaisePropertyChanged("COMPANY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckDeleteAttend {
            get {
                return this.CheckDeleteAttendField;
            }
            set {
                if ((this.CheckDeleteAttendField.Equals(value) != true)) {
                    this.CheckDeleteAttendField = value;
                    this.RaisePropertyChanged("CheckDeleteAttend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckError {
            get {
                return this.CheckErrorField;
            }
            set {
                if ((this.CheckErrorField.Equals(value) != true)) {
                    this.CheckErrorField = value;
                    this.RaisePropertyChanged("CheckError");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckFixOt {
            get {
                return this.CheckFixOtField;
            }
            set {
                if ((this.CheckFixOtField.Equals(value) != true)) {
                    this.CheckFixOtField = value;
                    this.RaisePropertyChanged("CheckFixOt");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CheckTime {
            get {
                return this.CheckTimeField;
            }
            set {
                if ((this.CheckTimeField.Equals(value) != true)) {
                    this.CheckTimeField = value;
                    this.RaisePropertyChanged("CheckTime");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool CreateAttend {
            get {
                return this.CreateAttendField;
            }
            set {
                if ((this.CreateAttendField.Equals(value) != true)) {
                    this.CreateAttendField = value;
                    this.RaisePropertyChanged("CreateAttend");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPT_B {
            get {
                return this.DEPT_BField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPT_BField, value) != true)) {
                    this.DEPT_BField = value;
                    this.RaisePropertyChanged("DEPT_B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string DEPT_E {
            get {
                return this.DEPT_EField;
            }
            set {
                if ((object.ReferenceEquals(this.DEPT_EField, value) != true)) {
                    this.DEPT_EField = value;
                    this.RaisePropertyChanged("DEPT_E");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateBegin {
            get {
                return this.DateBeginField;
            }
            set {
                if ((this.DateBeginField.Equals(value) != true)) {
                    this.DateBeginField = value;
                    this.RaisePropertyChanged("DateBegin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.DateTime DateEnd {
            get {
                return this.DateEndField;
            }
            set {
                if ((this.DateEndField.Equals(value) != true)) {
                    this.DateEndField = value;
                    this.RaisePropertyChanged("DateEnd");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string FixYymm {
            get {
                return this.FixYymmField;
            }
            set {
                if ((object.ReferenceEquals(this.FixYymmField, value) != true)) {
                    this.FixYymmField = value;
                    this.RaisePropertyChanged("FixYymm");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOBR_B {
            get {
                return this.NOBR_BField;
            }
            set {
                if ((object.ReferenceEquals(this.NOBR_BField, value) != true)) {
                    this.NOBR_BField = value;
                    this.RaisePropertyChanged("NOBR_B");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOBR_E {
            get {
                return this.NOBR_EField;
            }
            set {
                if ((object.ReferenceEquals(this.NOBR_EField, value) != true)) {
                    this.NOBR_EField = value;
                    this.RaisePropertyChanged("NOBR_E");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalEndDay {
            get {
                return this.SalEndDayField;
            }
            set {
                if ((this.SalEndDayField.Equals(value) != true)) {
                    this.SalEndDayField = value;
                    this.RaisePropertyChanged("SalEndDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public ConsoleApp1.JbhrServiceCNReference46.SalaryConfig SalaryConfig {
            get {
                return this.SalaryConfigField;
            }
            set {
                if ((object.ReferenceEquals(this.SalaryConfigField, value) != true)) {
                    this.SalaryConfigField = value;
                    this.RaisePropertyChanged("SalaryConfig");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_IDField, value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_NAME {
            get {
                return this.USER_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_NAMEField, value) != true)) {
                    this.USER_NAMEField = value;
                    this.RaisePropertyChanged("USER_NAME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isContinue {
            get {
                return this.isContinueField;
            }
            set {
                if ((this.isContinueField.Equals(value) != true)) {
                    this.isContinueField = value;
                    this.RaisePropertyChanged("isContinue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool isFixYymm {
            get {
                return this.isFixYymmField;
            }
            set {
                if ((this.isFixYymmField.Equals(value) != true)) {
                    this.isFixYymmField = value;
                    this.RaisePropertyChanged("isFixYymm");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SalaryConfig", Namespace="http://schemas.datacontract.org/2004/07/JBHRService")]
    [System.SerializableAttribute()]
    public partial class SalaryConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATTAWARDSALCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int AttEndDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int DecimalsField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EATSALCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EMPSALCODEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private int SalEndDayField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal WELPAYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string WELSALCODEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATTAWARDSALCODE {
            get {
                return this.ATTAWARDSALCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.ATTAWARDSALCODEField, value) != true)) {
                    this.ATTAWARDSALCODEField = value;
                    this.RaisePropertyChanged("ATTAWARDSALCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int AttEndDay {
            get {
                return this.AttEndDayField;
            }
            set {
                if ((this.AttEndDayField.Equals(value) != true)) {
                    this.AttEndDayField = value;
                    this.RaisePropertyChanged("AttEndDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int Decimals {
            get {
                return this.DecimalsField;
            }
            set {
                if ((this.DecimalsField.Equals(value) != true)) {
                    this.DecimalsField = value;
                    this.RaisePropertyChanged("Decimals");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EATSALCODE {
            get {
                return this.EATSALCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.EATSALCODEField, value) != true)) {
                    this.EATSALCODEField = value;
                    this.RaisePropertyChanged("EATSALCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EMPSALCODE {
            get {
                return this.EMPSALCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.EMPSALCODEField, value) != true)) {
                    this.EMPSALCODEField = value;
                    this.RaisePropertyChanged("EMPSALCODE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int SalEndDay {
            get {
                return this.SalEndDayField;
            }
            set {
                if ((this.SalEndDayField.Equals(value) != true)) {
                    this.SalEndDayField = value;
                    this.RaisePropertyChanged("SalEndDay");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal WELPAY {
            get {
                return this.WELPAYField;
            }
            set {
                if ((this.WELPAYField.Equals(value) != true)) {
                    this.WELPAYField = value;
                    this.RaisePropertyChanged("WELPAY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string WELSALCODE {
            get {
                return this.WELSALCODEField;
            }
            set {
                if ((object.ReferenceEquals(this.WELSALCODEField, value) != true)) {
                    this.WELSALCODEField = value;
                    this.RaisePropertyChanged("WELSALCODE");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransCardConfig", Namespace="http://schemas.datacontract.org/2004/07/JBHRService")]
    [System.SerializableAttribute()]
    public partial class TransCardConfig : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string GetDateValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OtBonusExceptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string GetDateValue {
            get {
                return this.GetDateValueField;
            }
            set {
                if ((object.ReferenceEquals(this.GetDateValueField, value) != true)) {
                    this.GetDateValueField = value;
                    this.RaisePropertyChanged("GetDateValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string OtBonusException {
            get {
                return this.OtBonusExceptionField;
            }
            set {
                if ((object.ReferenceEquals(this.OtBonusExceptionField, value) != true)) {
                    this.OtBonusExceptionField = value;
                    this.RaisePropertyChanged("OtBonusException");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="UserIdentity", Namespace="http://schemas.datacontract.org/2004/07/JBHR.Sal.Service")]
    [System.SerializableAttribute()]
    public partial class UserIdentity : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool ADMINField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string COMPANYField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_IDField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string USER_NAMEField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool ADMIN {
            get {
                return this.ADMINField;
            }
            set {
                if ((this.ADMINField.Equals(value) != true)) {
                    this.ADMINField = value;
                    this.RaisePropertyChanged("ADMIN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string COMPANY {
            get {
                return this.COMPANYField;
            }
            set {
                if ((object.ReferenceEquals(this.COMPANYField, value) != true)) {
                    this.COMPANYField = value;
                    this.RaisePropertyChanged("COMPANY");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_ID {
            get {
                return this.USER_IDField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_IDField, value) != true)) {
                    this.USER_IDField = value;
                    this.RaisePropertyChanged("USER_ID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string USER_NAME {
            get {
                return this.USER_NAMEField;
            }
            set {
                if ((object.ReferenceEquals(this.USER_NAMEField, value) != true)) {
                    this.USER_NAMEField = value;
                    this.RaisePropertyChanged("USER_NAME");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TransAttCardResult", Namespace="http://schemas.datacontract.org/2004/07/JBHRService")]
    [System.SerializableAttribute()]
    public partial class TransAttCardResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMsgField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool IsFinishField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StackTraceField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMsg {
            get {
                return this.ErrorMsgField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMsgField, value) != true)) {
                    this.ErrorMsgField = value;
                    this.RaisePropertyChanged("ErrorMsg");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool IsFinish {
            get {
                return this.IsFinishField;
            }
            set {
                if ((this.IsFinishField.Equals(value) != true)) {
                    this.IsFinishField = value;
                    this.RaisePropertyChanged("IsFinish");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string StackTrace {
            get {
                return this.StackTraceField;
            }
            set {
                if ((object.ReferenceEquals(this.StackTraceField, value) != true)) {
                    this.StackTraceField = value;
                    this.RaisePropertyChanged("StackTrace");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OtherAttendChangeInfo", Namespace="http://schemas.datacontract.org/2004/07/JBHRService.Attend")]
    [System.SerializableAttribute()]
    public partial class OtherAttendChangeInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ADATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ATYPEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BTIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string EDATEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ETIMEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string KEY_MANField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOBRField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NOTEField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private decimal USEMINField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ADATE {
            get {
                return this.ADATEField;
            }
            set {
                if ((object.ReferenceEquals(this.ADATEField, value) != true)) {
                    this.ADATEField = value;
                    this.RaisePropertyChanged("ADATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ATYPE {
            get {
                return this.ATYPEField;
            }
            set {
                if ((object.ReferenceEquals(this.ATYPEField, value) != true)) {
                    this.ATYPEField = value;
                    this.RaisePropertyChanged("ATYPE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BDATE {
            get {
                return this.BDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.BDATEField, value) != true)) {
                    this.BDATEField = value;
                    this.RaisePropertyChanged("BDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string BTIME {
            get {
                return this.BTIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.BTIMEField, value) != true)) {
                    this.BTIMEField = value;
                    this.RaisePropertyChanged("BTIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string EDATE {
            get {
                return this.EDATEField;
            }
            set {
                if ((object.ReferenceEquals(this.EDATEField, value) != true)) {
                    this.EDATEField = value;
                    this.RaisePropertyChanged("EDATE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ETIME {
            get {
                return this.ETIMEField;
            }
            set {
                if ((object.ReferenceEquals(this.ETIMEField, value) != true)) {
                    this.ETIMEField = value;
                    this.RaisePropertyChanged("ETIME");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string KEY_MAN {
            get {
                return this.KEY_MANField;
            }
            set {
                if ((object.ReferenceEquals(this.KEY_MANField, value) != true)) {
                    this.KEY_MANField = value;
                    this.RaisePropertyChanged("KEY_MAN");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOBR {
            get {
                return this.NOBRField;
            }
            set {
                if ((object.ReferenceEquals(this.NOBRField, value) != true)) {
                    this.NOBRField = value;
                    this.RaisePropertyChanged("NOBR");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string NOTE {
            get {
                return this.NOTEField;
            }
            set {
                if ((object.ReferenceEquals(this.NOTEField, value) != true)) {
                    this.NOTEField = value;
                    this.RaisePropertyChanged("NOTE");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public decimal USEMIN {
            get {
                return this.USEMINField;
            }
            set {
                if ((this.USEMINField.Equals(value) != true)) {
                    this.USEMINField = value;
                    this.RaisePropertyChanged("USEMIN");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="OtherAttendChangeServiceResult", Namespace="http://schemas.datacontract.org/2004/07/JBHRService.Attend")]
    [System.SerializableAttribute()]
    public partial class OtherAttendChangeServiceResult : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ErrorMessageField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private bool StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string ErrorMessage {
            get {
                return this.ErrorMessageField;
            }
            set {
                if ((object.ReferenceEquals(this.ErrorMessageField, value) != true)) {
                    this.ErrorMessageField = value;
                    this.RaisePropertyChanged("ErrorMessage");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool State {
            get {
                return this.StateField;
            }
            set {
                if ((this.StateField.Equals(value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="JbhrServiceCNReference46.IAttendanceService")]
    public interface IAttendanceService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/TimeTableGenerate", ReplyAction="http://tempuri.org/IAttendanceService/TimeTableGenerateResponse")]
        void TimeTableGenerate(string[] employeeList, string yymm, bool generateAttendance, string keyMan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/TimeTableGenerate", ReplyAction="http://tempuri.org/IAttendanceService/TimeTableGenerateResponse")]
        System.Threading.Tasks.Task TimeTableGenerateAsync(string[] employeeList, string yymm, bool generateAttendance, string keyMan);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/TransAttCard", ReplyAction="http://tempuri.org/IAttendanceService/TransAttCardResponse")]
        ConsoleApp1.JbhrServiceCNReference46.TransAttCardResult TransAttCard(ConsoleApp1.JbhrServiceCNReference46.TransAttCardEntry transAttCardEntry, ConsoleApp1.JbhrServiceCNReference46.TransCardConfig transCardConfig, ConsoleApp1.JbhrServiceCNReference46.UserIdentity userIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/TransAttCard", ReplyAction="http://tempuri.org/IAttendanceService/TransAttCardResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.JbhrServiceCNReference46.TransAttCardResult> TransAttCardAsync(ConsoleApp1.JbhrServiceCNReference46.TransAttCardEntry transAttCardEntry, ConsoleApp1.JbhrServiceCNReference46.TransCardConfig transCardConfig, ConsoleApp1.JbhrServiceCNReference46.UserIdentity userIdentity);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/GetCount", ReplyAction="http://tempuri.org/IAttendanceService/GetCountResponse")]
        int GetCount();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/GetCount", ReplyAction="http://tempuri.org/IAttendanceService/GetCountResponse")]
        System.Threading.Tasks.Task<int> GetCountAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/GetTest", ReplyAction="http://tempuri.org/IAttendanceService/GetTestResponse")]
        string GetTest(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/GetTest", ReplyAction="http://tempuri.org/IAttendanceService/GetTestResponse")]
        System.Threading.Tasks.Task<string> GetTestAsync(string data);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/AddOtherAttendChange", ReplyAction="http://tempuri.org/IAttendanceService/AddOtherAttendChangeResponse")]
        ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult AddOtherAttendChange(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/AddOtherAttendChange", ReplyAction="http://tempuri.org/IAttendanceService/AddOtherAttendChangeResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult> AddOtherAttendChangeAsync(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/CheckOtherAttendData", ReplyAction="http://tempuri.org/IAttendanceService/CheckOtherAttendDataResponse")]
        ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult CheckOtherAttendData(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IAttendanceService/CheckOtherAttendData", ReplyAction="http://tempuri.org/IAttendanceService/CheckOtherAttendDataResponse")]
        System.Threading.Tasks.Task<ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult> CheckOtherAttendDataAsync(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IAttendanceServiceChannel : ConsoleApp1.JbhrServiceCNReference46.IAttendanceService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AttendanceServiceClient : System.ServiceModel.ClientBase<ConsoleApp1.JbhrServiceCNReference46.IAttendanceService>, ConsoleApp1.JbhrServiceCNReference46.IAttendanceService {
        
        public AttendanceServiceClient() {
        }
        
        public AttendanceServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AttendanceServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttendanceServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AttendanceServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void TimeTableGenerate(string[] employeeList, string yymm, bool generateAttendance, string keyMan) {
            base.Channel.TimeTableGenerate(employeeList, yymm, generateAttendance, keyMan);
        }
        
        public System.Threading.Tasks.Task TimeTableGenerateAsync(string[] employeeList, string yymm, bool generateAttendance, string keyMan) {
            return base.Channel.TimeTableGenerateAsync(employeeList, yymm, generateAttendance, keyMan);
        }
        
        public ConsoleApp1.JbhrServiceCNReference46.TransAttCardResult TransAttCard(ConsoleApp1.JbhrServiceCNReference46.TransAttCardEntry transAttCardEntry, ConsoleApp1.JbhrServiceCNReference46.TransCardConfig transCardConfig, ConsoleApp1.JbhrServiceCNReference46.UserIdentity userIdentity) {
            return base.Channel.TransAttCard(transAttCardEntry, transCardConfig, userIdentity);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.JbhrServiceCNReference46.TransAttCardResult> TransAttCardAsync(ConsoleApp1.JbhrServiceCNReference46.TransAttCardEntry transAttCardEntry, ConsoleApp1.JbhrServiceCNReference46.TransCardConfig transCardConfig, ConsoleApp1.JbhrServiceCNReference46.UserIdentity userIdentity) {
            return base.Channel.TransAttCardAsync(transAttCardEntry, transCardConfig, userIdentity);
        }
        
        public int GetCount() {
            return base.Channel.GetCount();
        }
        
        public System.Threading.Tasks.Task<int> GetCountAsync() {
            return base.Channel.GetCountAsync();
        }
        
        public string GetTest(string data) {
            return base.Channel.GetTest(data);
        }
        
        public System.Threading.Tasks.Task<string> GetTestAsync(string data) {
            return base.Channel.GetTestAsync(data);
        }
        
        public ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult AddOtherAttendChange(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo) {
            return base.Channel.AddOtherAttendChange(otherAttendInfo);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult> AddOtherAttendChangeAsync(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo) {
            return base.Channel.AddOtherAttendChangeAsync(otherAttendInfo);
        }
        
        public ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult CheckOtherAttendData(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo) {
            return base.Channel.CheckOtherAttendData(otherAttendInfo);
        }
        
        public System.Threading.Tasks.Task<ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeServiceResult> CheckOtherAttendDataAsync(ConsoleApp1.JbhrServiceCNReference46.OtherAttendChangeInfo otherAttendInfo) {
            return base.Channel.CheckOtherAttendDataAsync(otherAttendInfo);
        }
    }
}
